name: Import
description: Import
inputs:
  path:
    description: Path
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install GodotEnv
      shell: bash
      run: |
        dotnet tool install --global Chickensoft.GodotEnv

    - name: Prep
      shell: bash
      run: |
        ls -R
        cd imgui-godot-* || true
        cd ${{ inputs.path }}
        godotenv addons install
        if [[ -f addons/imgui-godot/imgui-godot-native.gdextension ]]; then
          mkdir .godot
          echo "res://addons/imgui-godot/imgui-godot-native.gdextension" > .godot/extension_list.cfg
          cat .godot/*
        fi
        ls -RL
        $GODOT --headless --import || true
        echo "GAMEDIR=$(pwd)" >> $GITHUB_ENV
