using Godot;
using Godot.Collections;
using ImGuiNET;

public static class ImGuiInput
{
    public static readonly Dictionary<Key, ImGuiKey> KeyMap = new()
    {
        { Key.Tab, ImGuiKey.Tab },
        { Key.Left, ImGuiKey.LeftArrow },
        { Key.Right, ImGuiKey.RightArrow },
        { Key.Up, ImGuiKey.UpArrow },
        { Key.Down, ImGuiKey.DownArrow },
        { Key.Pageup, ImGuiKey.PageUp },
        { Key.Pagedown, ImGuiKey.PageDown },
        { Key.Home, ImGuiKey.Home },
        { Key.End, ImGuiKey.End },
        { Key.Insert, ImGuiKey.Insert },
        { Key.Delete, ImGuiKey.Delete },
        { Key.Backspace, ImGuiKey.Backspace },
        { Key.Space, ImGuiKey.Space },
        { Key.Enter, ImGuiKey.Enter },
        { Key.Escape, ImGuiKey.Escape },
        { Key.Menu, ImGuiKey.Menu },
        { Key.Key0, ImGuiKey._0 },
        { Key.Key1, ImGuiKey._1 },
        { Key.Key2, ImGuiKey._2 },
        { Key.Key3, ImGuiKey._3 },
        { Key.Key4, ImGuiKey._4 },
        { Key.Key5, ImGuiKey._5 },
        { Key.Key6, ImGuiKey._6 },
        { Key.Key7, ImGuiKey._7 },
        { Key.Key8, ImGuiKey._8 },
        { Key.Key9, ImGuiKey._9 },
        { Key.Apostrophe, ImGuiKey.Apostrophe },
        { Key.Comma, ImGuiKey.Comma },
        { Key.Minus, ImGuiKey.Minus },
        { Key.Period, ImGuiKey.Period },
        { Key.Slash, ImGuiKey.Slash },
        { Key.Semicolon, ImGuiKey.Semicolon },
        { Key.Equal, ImGuiKey.Equal },
        { Key.Bracketleft, ImGuiKey.LeftBracket },
        { Key.Backslash, ImGuiKey.Backslash },
        { Key.Bracketright, ImGuiKey.RightBracket },
        { Key.Quoteleft, ImGuiKey.GraveAccent },
        { Key.Capslock, ImGuiKey.CapsLock },
        { Key.Scrolllock, ImGuiKey.ScrollLock },
        { Key.Numlock, ImGuiKey.NumLock },
        { Key.Print, ImGuiKey.PrintScreen },
        { Key.Pause, ImGuiKey.Pause },
        { Key.Kp0, ImGuiKey.Keypad0 },
        { Key.Kp1, ImGuiKey.Keypad1 },
        { Key.Kp2, ImGuiKey.Keypad2 },
        { Key.Kp3, ImGuiKey.Keypad3 },
        { Key.Kp4, ImGuiKey.Keypad4 },
        { Key.Kp5, ImGuiKey.Keypad5 },
        { Key.Kp6, ImGuiKey.Keypad6 },
        { Key.Kp7, ImGuiKey.Keypad7 },
        { Key.Kp8, ImGuiKey.Keypad8 },
        { Key.Kp9, ImGuiKey.Keypad9 },
        { Key.KpPeriod, ImGuiKey.KeypadDecimal },
        { Key.KpDivide, ImGuiKey.KeypadDivide },
        { Key.KpMultiply, ImGuiKey.KeypadMultiply },
        { Key.KpSubtract, ImGuiKey.KeypadSubtract },
        { Key.KpAdd, ImGuiKey.KeypadAdd },
        { Key.KpEnter, ImGuiKey.KeypadEnter },
        { Key.A, ImGuiKey.A },
        { Key.B, ImGuiKey.B },
        { Key.C, ImGuiKey.C },
        { Key.D, ImGuiKey.D },
        { Key.E, ImGuiKey.E },
        { Key.F, ImGuiKey.F },
        { Key.G, ImGuiKey.G },
        { Key.H, ImGuiKey.H },
        { Key.I, ImGuiKey.I },
        { Key.J, ImGuiKey.J },
        { Key.K, ImGuiKey.K },
        { Key.L, ImGuiKey.L },
        { Key.M, ImGuiKey.M },
        { Key.N, ImGuiKey.N },
        { Key.O, ImGuiKey.O },
        { Key.P, ImGuiKey.P },
        { Key.Q, ImGuiKey.Q },
        { Key.R, ImGuiKey.R },
        { Key.S, ImGuiKey.S },
        { Key.T, ImGuiKey.T },
        { Key.U, ImGuiKey.U },
        { Key.V, ImGuiKey.V },
        { Key.W, ImGuiKey.W },
        { Key.X, ImGuiKey.X },
        { Key.Y, ImGuiKey.Y },
        { Key.Z, ImGuiKey.Z },
        { Key.F1, ImGuiKey.F1 },
        { Key.F2, ImGuiKey.F2 },
        { Key.F3, ImGuiKey.F3 },
        { Key.F4, ImGuiKey.F4 },
        { Key.F5, ImGuiKey.F5 },
        { Key.F6, ImGuiKey.F6 },
        { Key.F7, ImGuiKey.F7 },
        { Key.F8, ImGuiKey.F8 },
        { Key.F9, ImGuiKey.F9 },
        { Key.F10, ImGuiKey.F10 },
        { Key.F11, ImGuiKey.F11 },
        { Key.F12, ImGuiKey.F12 },
    };

    public static readonly Dictionary<JoyButton, ImGuiKey> JoypadButtonMap = new()
    {
        { JoyButton.Start, ImGuiKey.GamepadStart },
        { JoyButton.Back, ImGuiKey.GamepadBack },
        { JoyButton.Y, ImGuiKey.GamepadFaceUp },
        { JoyButton.A, ImGuiKey.GamepadFaceDown },
        { JoyButton.X, ImGuiKey.GamepadFaceLeft },
        { JoyButton.B, ImGuiKey.GamepadFaceRight },
        { JoyButton.DpadUp, ImGuiKey.GamepadDpadUp },
        { JoyButton.DpadDown, ImGuiKey.GamepadDpadDown },
        { JoyButton.DpadLeft, ImGuiKey.GamepadDpadLeft },
        { JoyButton.DpadRight, ImGuiKey.GamepadDpadRight },
        { JoyButton.LeftShoulder, ImGuiKey.GamepadL1 },
        { JoyButton.RightShoulder, ImGuiKey.GamepadR1 },
        { JoyButton.LeftStick, ImGuiKey.GamepadL3 },
        { JoyButton.RightStick, ImGuiKey.GamepadR3 },
    };

}

