name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    env:
      DemoProj: Dear ImGui for Godot Demo.csproj

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Format
      run: dotnet format --no-restore --verify-no-changes "${{ env.DemoProj }}" || (dotnet format --no-restore "${{ env.DemoProj }}" && git diff --color && exit 1)
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
