name: 🐧 Linux

# TODO: upload *.so as artifacts

on:
  push:
    branches-ignore:
      - godot3
  pull_request:
    branches-ignore:
      - godot3

env:
  VCPKG_ROOT: "${{ github.workspace }}/vcpkg"
  source: "${{ github.workspace }}/doc/cpp-demo"
  build: "${{ github.workspace }}/doc/cpp-demo/build.debug"
  preset: debug
  config: Debug

jobs:
  analyze:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Linux deps
        run: sudo apt-get install ninja-build

      - uses: actions/checkout@v3
      
      - name: clang-format
        working-directory: ${{ env.source }}
        run: clang-format --verbose --dry-run --Werror $(git ls-files -- '*.cpp' '*.h')
        
      - name: Get vcpkg
        run: |
          git clone -n https://github.com/microsoft/vcpkg
          cd vcpkg
          git checkout 2022.11.14
          ./bootstrap-vcpkg.sh

      - name: CMake Configure
        run: cmake --preset ${{ env.preset }} ${{ env.source }}
        
      - name: CMake Build
        run: cmake --build ${{ env.build }} --config ${{ env.config }} --target install
        
      - name: CMake Test
        working-directory: ${{ env.build }}
        run: ctest -C ${{env.config}}
