name: MSVC

# TODO: upload dlls as artifact

on:
  push:
    branches-ignore:
      - godot3
  pull_request:
    branches-ignore:
      - godot3

env:
  VCPKG_ROOT: "${{ github.workspace }}/vcpkg"
  build: "${{ github.workspace }}/doc/cpp-demo/msvc.debug"
  config: Debug

jobs:
  analyze:
    name: Build and Analyze
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Get vcpkg
        run: |
          git clone -n https://github.com/microsoft/vcpkg
          cd vcpkg
          git checkout 2022.11.14
          .\bootstrap-vcpkg.bat

      - name: Configure CMake
        run: cmake --preset msvc.debug doc/cpp-demo
        
      - name: CMake Build
        run: cmake --build ${{ env.build }} --config ${{ env.config }} --target install

      - name: Run MSVC Code Analysis
        uses: microsoft/msvc-code-analysis-action@v0.1.1
        id: run-analysis
        with:
          cmakeBuildDirectory: ${{ env.build }}
          buildConfiguration: ${{ env.config }}
          ignoredPaths: ${{ env.build }}/_deps
          ruleset: NativeRecommendedRules.ruleset

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.run-analysis.outputs.sarif }}

      - name: Upload SARIF as an Artifact
        uses: actions/upload-artifact@v2
        with:
          name: sarif-file
          path: ${{ steps.run-analysis.outputs.sarif }}
