name: Microsoft C++ Code Analysis

on:
  push:
    branches-ignore:
      - godot3
  pull_request:
    branches-ignore:
      - godot3

env:
  VCPKG_ROOT: "${{ runner.temp }}/vcpkg"

permissions:
  contents: read

jobs:
  analyze:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    name: Analyze
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Get vcpkg
        run: |
          cd ${{ runner.temp }}
          git clone https://github.com/microsoft/vcpkg
          cd vcpkg
          git checkout 2022.11.14
          .\bootstrap-vcpkg.bat

      - name: Configure CMake
        run: cmake --preset msvc.debug doc/cpp-demo

      - name: Initialize MSVC Code Analysis
        uses: microsoft/msvc-code-analysis-action@04825f6d9e00f87422d6bf04e1a38b1f3ed60d99
        # Provide a unique ID to access the sarif output path
        id: run-analysis
        with:
          cmakeBuildDirectory: doc/cpp-demo/msvc.debug
          # Ruleset file that will determine what checks will be run
          ruleset: NativeRecommendedRules.ruleset

      # Upload SARIF file to GitHub Code Scanning Alerts
      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.run-analysis.outputs.sarif }}

