[package]
name = "gdextrust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = [ "cdylib" ]

[dependencies]
godot = "0.1.3"

[build-dependencies]
bindgen = "0.70.1"
cc = "1.2.1"
cmd_lib = "1.9.5"
glob = "0.3.1"
